"""M11 — PR output. A verified fix is surfaced as a reviewable pull request whose
body carries the EXPLOIT TEST as evidence, for the human merge gate.

In the slice this produces the PR artifact (title + markdown body + the diff);
in production the same payload is opened via `gh`/the GitHub API. The point is
that a human never has to trust the agent — the PR shows the exploit was blocked
and the legitimate path preserved, each an executed check.
"""
from __future__ import annotations

from dataclasses import dataclass

_CLASS_TITLE = {
    "BOLA": "broken object level authorization",
    "BFLA": "broken function level authorization",
    "MASS_ASSIGNMENT": "mass assignment",
    "SSRF": "server-side request forgery",
    "MISSING_AUTH": "missing authentication",
}


@dataclass
class PRDraft:
    title: str
    body: str

    def write(self, path: str):
        with open(path, "w") as f:
            f.write(f"# {self.title}\n\n{self.body}\n")


def make_pr_draft(app: str, result, exploit_name: str = "exploit.py") -> PRDraft | None:
    """Build a PR draft for a verified fix. Returns None unless the fix passed
    exploit verification (we never open a PR for an unverified change)."""
    if result.status != "success":
        return None
    cls_desc = _CLASS_TITLE.get(result.issue_class, result.issue_class)
    title = f"fix(security): {result.issue_class} in {result.func} — {cls_desc}"

    diff = result.rendered_diff.strip()
    stages = "\n".join(
        f"- [{'x' if ok else ' '}] {name}" for name, ok in (result.stages or []))
    prov = {"template": "deterministic template",
            "fuzzy": "near-neighbor recall (promoted)",
            "llm_cold": "LLM cold-path (promoted to template)"}.get(
                result.provenance, result.provenance)

    body = f"""## Vulnerability
`{result.issue_class}` in `{app}::{result.func}` — {cls_desc}.
Fingerprint `{result.fp_hex}`.

## Fix
```diff
{diff}
```

## Exploit-verified evidence
Applied in a sandbox and checked by the validator stack (each an executed test):
{stages}

The attached exploit reproducer (`{exploit_name}`) **succeeds before** this patch
and **fails after** it; the legitimate path is preserved.

## Provenance
- source: {prov}
- selection posterior: {result.posterior:.3f}

---
*Generated by codefix. Requires human review + merge (approval gate).*"""
    return PRDraft(title, body)
